#!/bin/bash

hwmon_dir=/sys/devices/platform/coretemp.0/hwmon/hwmon*/
core_temps=`for temp in $(cd $hwmon_dir; ls | egrep "temp[2-99]_input"); do echo $(( $(<$hwmon_dir/$temp) / 1000 )); done`

index=0
for temp in $core_temps; do
    if [ $temp -ge 50 ]; then
	    color="yellow"
    elif [ $temp -ge 70 ]; then
        color="red"
    else
        color="#b380ff"
    fi
    if [ $index -gt 0 ]; then
        echo -n " "
    fi
    echo -n "<span color='$color'>CORE$index $temp"$'\xc2\xb0'C"</span>"
    let "index+=1"
done

echo

# vim: filetype=sh
