#!/bin/bash

hwmon_dir=/sys/devices/platform/coretemp.0/hwmon/hwmon*/
core_temps=`for temp in $(cd $hwmon_dir; ls | egrep "temp[2-99]_input"); do echo $(( $(<$hwmon_dir/$temp) / 1000 )); done`

index=0
for temp in $core_temps; do
    if [ $temp -ge 50 ]; then
	    color="yellow"
    elif [ $temp -ge 70 ]; then
        color="red"
    fi
    echo -n " "
    [[ ! -z $color ]] && "<span color='$color'>"
    echo -n "<small>C$index:</small><b>$temp"$'\xc2\xb0'C"</b>"
    [[ ! -z $color ]] && "</span>"
    let "index+=1"
done

echo

# vim: filetype=sh
