#!/bin/bash

full_minutes=$(echo `cat /proc/uptime | grep -o '^[0-9]\+'` / 60 | bc)
hours=$(echo $full_minutes / 60 | bc)
minutes=$(echo "$full_minutes - $hours * 60" | bc)

[[ $hours -ge 8 ]] && echo -n "<span color='#00cc00'>"
printf "%02dh%02d" $hours $minutes
[[ $hours -ge 8 ]] && echo "</span>"

echo

# vim: filetype=sh
